### ISSUE TITLE
Java calculadoraUTN videos 9.1, 9.2, 9.3

### ISSUE THREAD

**Issue by Natalia24v** [CodeSystem2022/Alibaba-Tercer-Semestre#158]
crear carpeta Semana9
Instalar Intellij. Crear new proyect calculadoraUTN que se ubicará en tecnicatura3Java /lección 09  **utiliza la versión openjdk-17**

- Eliminar el archivo main.
- Crear nueva java Class: calculadoraUTN 
- Definir variables: operando1, operando2 y resultado
- Añadir la clase Scanner entrada
- Hacer Pull Recuest y avisar al SM

**Comment by Gabibelt** [comment]
Listo señora
