### ISSUE TITLE
Java calculadoraUTN videos 9.4, 9.5,

### ISSUE THREAD

**Issue by Natalia24v** [CodeSystem2022/Alibaba-Tercer-Semestre#159]
- Agregar el menú 
- Agregar variable operación
- Agregar condicional IF
- Agregar Switch dentro del condicional IF con los case 1, 2, 3, 4 y default(para entradas erróneas)
- Ejecutar y comprobar su funcionamiento
Hacer Pull Recuest y avisar al SM

**Comment by lokywolf2295** [comment]
![image](https://github.com/CodeSystem2022/Alibaba-Tercer-Semestre/assets/95238399/437a7fb3-06d3-4fa2-8db8-fed9b931139d)

La taréa está lista para corregir y funcionando.

@Natalia24v
