### ISSUE TITLE
Subir ejercicio de Javascript

### ISSUE THREAD

**Issue by lokywolf2295** [CodeSystem2022/Alibaba-Tercer-Semestre#19]
Agregar Un (1) ejercicio realizado en otros lenguajes, pasado a Script, comitear y hacer el push al Remoto, la Pull Request en Github  de la Rama Semana 1 a la develop y avisar al Scrum Master de la Semana, que la tarea está realizada de manera correcta.

**Comment by Gabibelt** [comment]
Listo el commit a Semana-1
