### ISSUE TITLE
 Uso de with, archivos y contexto Manager Parte 2

### ISSUE THREAD

**Issue by angesc2022** [CodeSystem2022/Alibaba-Tercer-Semestre#26]
Agregar Uso de with, archivos y contexto Manager Parte 2  comitear y hacer el push al Remoto, la Pull Request en Github de la Rama Semana 2 a la develop y avisar al Scrum Master de la Semana, que la tarea está realizada de manera correcta. python, comitear y hacer el push al Remoto, la Pull Request en Github de la Rama Semana 2 a la develop y avisar al Scrum Master de la Semana, que la tarea está realizada de manera correcta.

**Comment by Gabibelt** [comment]
aqui vamos!

**Comment by Gabibelt** [comment]
FInalizada la tarea
