### ISSUE TITLE
JS-Modificar y agregar al archivo 01-03-funciones,  Argumentos y parámetros, Concepto hoisting, Paso por valor y Paso por referencia.

### ISSUE THREAD

**Issue by DenuArg** [CodeSystem2022/Alibaba-Tercer-Semestre#44]
JavaScript: Agregar al archivo 01-03-funciones.js de la carpeta Semana 3, lo trabajado en clases desde el video 7 al 9.1 inclusive de la Clase 3.
1.7 Argumentos y parámetros
1.8 Concepto hoisting
1.9 Paso por valor
1.9.1 Paso por referencia

Luego deberá realizar un Commit. Hacer el Push al Remoto, la Pull Request en Github de la Rama Semana 3 a la Develop y avisar al Scrum Master de la Semana que la tarea se efectuó de forma correcta.

**Comment by angesc2022** [comment]
Perfecto
