### ISSUE TITLE
Java-Crear carpeta Semana 3 - Cargar parte de los archivos clase 3.

### ISSUE THREAD

**Issue by DenuArg** [CodeSystem2022/Alibaba-Tercer-Semestre#48]
El primer integrante elegido para trabajar con este lenguaje, deberá en la carpeta de Java agregar la carpeta Semana 3 y subir lo trabajado en clases desde el video 1 hasta el video 4 inclusive, deberá subir los siguientes archivos:

- TestForEach
- Persona
- AutoBoxingUnboxing
- TestAutoBoxingUnboxing

Luego deberá realizar un Commit. Hacer el Push al Remoto, la Pull Request en Github de la Rama Semana 3 a la Develop y avisar al Scrum Master de la Semana que la tarea se efectuó de forma correcta.

**Comment by Gabibelt** [comment]
Perfecto ahí vamos

**Comment by DenuArg** [comment]
Cualquier duda o problema que surja no dudes en comunicarlo lo antes posible, así se podrá trabajar para superar los obstáculos. 
Saludos!

**Comment by angesc2022** [comment]
thanks you friend

**Comment by angesc2022** [comment]
Modificar y agregar al archivo 01-03-funciones, Argumentos y parámetros, Concepto hoisting, Paso por valor y Paso por referencia. (Issue #44)
