### ISSUE TITLE
Java-Cargar 2da parte de los archivos de la clase 3

### ISSUE THREAD

**Issue by DenuArg** [CodeSystem2022/Alibaba-Tercer-Semestre#49]
Subir los siguientes archivos a la carpeta de Java, semana 3, con lo trabajado en clase desde el video 5 al 10 inclusive:

- Clase1
- Clase2
- Clase3
- Clase4
- ClaseHija2
- TestDefault
- TestModificadoresAcceso

Luego deberá realizar un Commit. Hacer el Push al Remoto, la Pull Request en Github de la Rama Semana 3 a la Develop y avisar al Scrum Master de la Semana que la tarea se efectuó de forma correcta.

**Comment by Gabibelt** [comment]
Mati aca estan los archivos iniciales y solo queda mi parte es asi?
