### ISSUE TITLE
Python-Subir Conexión hacia la base de datos en Python con el método fetchall()-Cerramos la conexión y la consulta.

### ISSUE THREAD

**Issue by PabloYR16** [CodeSystem2022/Alibaba-Tercer-Semestre#62]
El integrante del Grupo, deberá subir los ejercicios correspondientes a la carpeta Semana 4 que se encuentra  dentro de la carpeta Python, a continuación se mostrara los ejercicios a realizar.
1.6 Conexión hacia la base de datos en Python con el método fetchall().
1.7 Cerramos la conexión y la consulta.
También deberá crear un tag  que tenga como nombre V0.4.3_FinalizaciónPython_Semana4. luego deberá realizar un Commit. Hacer el Push al Remoto, la Pull Request en Github de la Rama Semana 4 a la Develop y avisar al Scrum Master de la Semana que la tarea se efectuó de forma correcta.

**Comment by lokywolf2295** [comment]
@PabloYR16 Listo para que lo puedas controlar =D 🦾

**Comment by PabloYR16** [comment]
@lokywolf2295  ok =D
