### ISSUE TITLE
JS-Modificar y agregar al archivo 01-04-objectos.js, Ejecutamos desde el navegador, Distintas formas de imprimir un Objeto con: Object.values()  y JSON.stringify()

### ISSUE THREAD

**Issue by PabloYR16** [CodeSystem2022/Alibaba-Tercer-Semestre#66]
El integrante del grupo deberá agregar al archivo 01-04-objectos.js de la carpeta Semana 4,  los siguientes ejercicios.
1.6 Ejecutamos desde el navegador
1.7 Distintas formas de imprimir un Objeto con: Object.values()  y JSON.stringify()
También deberá crear un tag  que tenga como nombre V0.4.5_FinalizaciónJavascript_Semana4. luego deberá realizar un Commit. Hacer el Push al Remoto, la Pull Request en Github de la Rama Semana 4 a la Develop y avisar al Scrum Master de la Semana que la tarea se efectuó de forma correcta.

**Comment by angesc2022** [comment]
El integrante del grupo deberá agregar al archivo 01-04-objectos.js de la carpeta Semana 4, los siguientes ejercicios.
1.6 Ejecutamos desde el navegador
1.7 Distintas formas de imprimir un Objeto con: Object.values() y JSON.stringify()
También deberá crear un tag que tenga como nombre V0.4.5_FinalizaciónJavascript_Semana4. luego deberá realizar un Commit. Hacer el Push al Remoto, la Pull Request en Github de la Rama Semana 4 a la Develop y avisar al Scrum Master de la Semana que la tarea se efectuó de forma correcta.
