### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Frojas0** [CodeSystem2022/Alibaba-Tercer-Semestre#74]

**Comment by lokywolf2295** [comment]
@Frojas0 te equivocaste de grupo jajajaj te aviso por las dudas

**Comment by Frojas0** [comment]
Si Mati, gracias por avisar, estaba asignando las tareas para dejarlas en las tablas hechas y meti mal el dedo, por eso no esta bueno que los repositorios sean publicos. Disculpa y gracias por avisar

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
