### ISSUE TITLE
JavaScript (1 de 2)

### ISSUE THREAD

**Issue by Jorge-Huaman** [CodeSystem2022/Alibaba-Tercer-Semestre#85]
La persona asignada deberá :

- Crear la carpeta de la semana 5 , pegar los archivos 01-04-objetos.js e index.html creados en la semana 04
- Modificar el archivo 01-04-objetos.js  (videos 1, 2 ,3 , 4)
- realizar un Commit. Hacer el Push al Remoto, la Pull Request en Github de la Rama Semana 5 a la Develop y avisar al Scrum Master de la Semana que la tarea se efectuó de forma correcta.

Temas: 
5.1 Métodos get y set Parte 1 y 2
5.2 Constructores de objetos
5.3 Agregar métodos al constructor del objeto

Archivo: 
01-04-objetos.js

**Comment by lokywolf2295** [comment]
@Jorge-Huaman  listo mi parte para ser revisada
