### ISSUE TITLE
JavaScript (2 de 2)

### ISSUE THREAD

**Issue by Jorge-Huaman** [CodeSystem2022/Alibaba-Tercer-Semestre#86]
La persona asignada deberá :

- Modificar el archivo 01-04-objetos.js (videos 5, 6, 7, 8)
- realizar un Commit. Hacer el Push al Remoto, la Pull Request en Github de la Rama Semana 5 a la Develop y avisar al Scrum Master de la Semana que la tarea se efectuó de forma correcta.

Temas: 
5.4 Distintas formas de crear objetos
5.5 El uso de prototype
5.6 El uso de call
5.7 El uso de apply

Archivo: 
01-04-objetos.js

**Comment by DenuArg** [comment]
Entendido!
